### ISSUE TITLE
Error: You are using the following variables which haven't been populated: buildDate...

### ISSUE THREAD

**Issue by hotdang-ca** [fknussel/webpack-version-file#5]
Seems that v0.1.4 introduced changes where the context of `buildDate` in the template is no longer accessible.

Up to v0.1.3, this config worked:
```js
config.plugins.push(
    new VersionFile({
        output: path.resolve(paths.old_web_proj, 'ViewModels/Version', 'AppVersionCurrent.cs'),
        templateString: '//generated by __filename webpack.prod.config.js\n' +
                        'namespace StrangeBrew.Web.ViewModels.Version\n' +
                        '{\n' +
                        '    public partial class AppVersion\n' +
                        '    {\n' +
                        '        public static readonly AppVersion Current = new AppVersion(\n' +
                        '                name: "<%= name %>",\n' +
                        '                version: "<%= version %>",\n' +
                        '                year: <%= buildDate.getYear()+1900 %>,\n' +
                        '                month: <%= buildDate.getMonth()+1 %>,\n' +
                        '                day: <%= buildDate.getDate() %>,\n' +
                        '                hour: <%= buildDate.getHours() %>,\n' +
                        '                minute: <%= buildDate.getMinutes() %>,\n' +
                        '                gmtOffsetMinutes: <%= buildDate.getTimezoneOffset() %>);\n' +
                        '    }\n' +
                        '}'
    }),
    new VersionFile({
        output:  path.resolve(paths.src, 'data/stores/', 'version.ts'),
        templateString: "import {IAppVersion} from './IAppVersion';\n\n" +
        "export const BrewNinjaAppVersion: IAppVersion = { \n" +
        "    Name: '<%= name %>', \n" +
        "    Version: '<%= version %>', \n" +
        "    Date: '<%= buildDate %>' \n" +
        "};"
    }),

    new webpack.DefinePlugin({
        "process.env": {
            NODE_ENV: JSON.stringify("production"),
        }
    })
);
```

v0.1.4 generates the above error, with no other code changes other than updated version. Stacktrace:
```
 at VersionFile.apply (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack-version-file\lib\index.js:97:15)
    at webpack (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack\lib\webpack.js:51:13)
    at processOptions (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack-cli\bin\cli.js:272:16)
    at yargs.parse (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack-cli\bin\cli.js:364:3)
    at Object.parse (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\yargs\yargs.js:567:18)
    at C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\jperi\Developer\BrewNinja\StrangeBrewWeb\StrangeBrew.App\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Recommend re-tagging as v0.2.0 so that `^0.1.3` references in package.json don't inadvertently update to v0.1.4.

**Comment by fed** [comment]
Hey @hotdang-ca thanks a lot for reporting this and providing so many details on the issue! I'm sorry this has suddently stopped working, it was not intended to be a breaking change -- I just wanted to add some better error handling and overlooked the fact that variables could be objects themselves. I've just published `webpack-version-file@0.1.5` which should fix the issue. Can you please give it a go and let me know? Cheers 🙌

**Comment by hotdang-ca** [comment]
I'll do this today, and let you know :)

**Comment by fed** [comment]
Hey @hotdang-ca have you had the chance to test this? Thank you 🙂
